config/routes.rb
Risd::Application.routes.draw do
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show]
  resources :events, :only => [:show, :new, :create, :destroy] do
    resources :uploads, :only => [:index, :show, :create, :destroy]
    resources :publicity_emails, :only => [:show, :create]
    member do
      get 'publicity'
      get 'yelp'
      post 'yelp_search'
      post 'select_restaurant'
      post 'deselect_restaurant'
      delete 'clear_restaurants'
    end
  end
  resources :checklist_items, :only => [:create, :destroy] do
    post 'edit_text', :on => :collection
    post 'toggle_checked', :on => :member
  end
  resources :tags, :only => [:create, :destroy]
  resources :budget_items, :only => [:index, :create, :destroy]

  post "/events/:event_id/uploadFromRedactor" => "uploads#create_from_redactor"
  match "/events/:event_id/images" => "uploads#images", :as => "event_images"
  get "/settime/:id" => "events#new_time"
  post "/settime/:id" => "events#set_time"
  get "/getevents" => "events#getevents"
  get "/getresources" => "events#getresources"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :club_name, :email, :password, :password_confirmation, :remember_me, :confirmed_at
  
  # Validation that email is in ASA student group exec DB
  validate :must_be_asa_group_email

  after_create :prepopulate_tags
  
  has_many :events
  has_many :tags

  # before created a user, validate that it is a asa group by checking the
  # email against our database of asa group exec emails.
  def must_be_asa_group_email
    if not AsaDb.find(:all).collect(&:email).include?(email)
      errors.add(:email, "is not a valid ASA student group officer mailing list.")
    else
      self.club_name = AsaDb.find_by_email(self.email).name
    end
  end

  # when a user is created, extract the tags that are paired with the user's group
  # and associate those with the newly created user.
  def prepopulate_tags
    preprocessed_tags = AsaDb.find_by_name(self.club_name).unprocessed_tags
    if preprocessed_tags != nil
      preprocessed_tags.split(",").each do |tag|
        self.tags.create(:name => tag)
      end
    end
  end

  # find which tags of this user match "fuzzily" with yelp restaurant categories.
  def cross_reference_tags_and_sample
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)
    matched_tags = []
    self.tags.each do |tag|
      YELP_API_CATEGORIES.map{|category| jarow.getDistance(tag.name, category)}.each_with_index do |score, index|
        if score >= 0.9
          matched_tags << YELP_API_CATEGORIES[index]
        end
      end
    end
    matched_tags.sample
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  # controller action for the dashboard
  # passes in the current user and a new event object to create a new event
  # requires that a user is logged in
  def show
    @user = current_user
    @event = @user.events.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
.eight.columns.centered
  .one.columns.dashboard-title
    %i.general.foundicon-graph
  .eight.columns.dashboard-title
    %h1.dashboard-title
      Events Dashboard
  .three.columns.dashboard-title
    = button_to "+ Create New Event", "/new_event", :class => "success button", :style => "align:right;", :id => "createEventModalButton"
  %hr
  .twelve.columns
    .no-bullet-area
      %ul
        - if current_user.events.count == 0
          .panel
            %h3.subtitle You currently don't have any events - make one!
        - else
          - current_user.events.order("id DESC").each_with_index do |event, index|
            .panel.radius
              %li{:class => "#{index == 0 ? 'active' : ''}"}
                .title
                  %h3
                    = event.title
                  %h6.subtitle
                    - if event.time_block.starttime != DateTime.new(1,1,1,1,1)
                      = event.time_block.starttime.strftime("%m/%d/%Y %I:%M %p") + " to " + event.time_block.endtime.strftime("%m/%d/%Y %I:%M %p")
                    - else
                      No time set for event yet.
                %hr
                .content
                  %div{:id => "existing-checklist-items-" + event.id.to_s}
                    - event.checklist_items.order("id").each do |checklist_item|
                      %div{:id => "checklist-item-" + checklist_item.id.to_s, :style => "padding-left:10px;"}
                        %i{:class => "general #{checklist_item.checked? ? 'foundicon-checkmark checked' : 'foundicon-remove unchecked'}", :id => checklist_item.id, :type => "checklist"}
                        %span{:class => "#{checklist_item.checked? ? 'strikethrough' : 'bold'}"}
                          - if checklist_item.tag == 'datetime'
                            = link_to checklist_item.text, "/settime/#{event.id}", :class => "checklist-link"
                          - elsif checklist_item.tag == 'filemanager'
                            = link_to checklist_item.text, event_uploads_path(event), :class => "checklist-link"
                          - elsif checklist_item.tag == 'publicity'
                            = link_to checklist_item.text, publicity_event_path(event), :class => "checklist-link"
                          - elsif checklist_item.tag == 'food'
                            = link_to checklist_item.text, "/events/#{event.id}/yelp", :class => "checklist-link"
                          - elsif checklist_item.tag == 'copytech'
                            = link_to checklist_item.text, "http://copytech-print.mit.edu/fulfillment/login", :class => "checklist-link", :target => "_blank" 
                          - elsif checklist_item.tag == 'budget'
                            = link_to checklist_item.text, "/budget_items?id=" + event.id.to_s, :class => "checklist-link"
                          - else
                            %span{:class => "editableitem", :id => checklist_item.id.to_s}
                              = checklist_item.text
                        %span.right-align
                          = link_to "Delete", "#", :id => checklist_item.id.to_s, :class => "delete-checklist-item", data: {confirm: "Are you sure you want to delete this checklist item?"}
                        %br
                  %i{:class => "general foundicon-plus add dashboard"}
                  = text_field_tag(event.id, nil, :placeholder => 'Type in a new checklist item for ' + event.title + ".", :class => "new-checklist-item")
                .footer
                  %hr
                  = link_to "Delete Event", event, method: :delete, data: {confirm: 'Are you sure?' }

#createEventModal.reveal-modal.medium
  %h2 Create a New Event
  = simple_form_for @event, :url => "/events" do |f|
    = f.error_notification
    = f.input :title
    = f.input :description

    = f.submit 'Create Event', :class => 'button'
  %a.close-reveal-modal x